//xlld.framework,xlld.memorymanager,xlld.memorypool,xlld.worksheet,xlld.wrap,xlld.xlcall,xlld.xlcallcpp,xlld.xll
//Automatically generated by unit_threaded.gen_ut_main, do not edit by hand.
import unit_threaded;

int main(string[] args)
{
    return args.runTests!(
        "xlld.worksheet",
        "xlld.traits",
        "xlld.wrap",
        "xlld.xl",
        "xlld.xll",
        "xlld.memorymanager",
        "xlld.test_util",
        "xlld.xlf",
        "xlld.conv.misc",
        "xlld.any",
    );
}
